[variables]
NODE_ENV = "development"

[phases.build]
cmds = ["npm install --include=dev", "npx prisma generate", "npm run build"]

[phases.setup]
aptPkgs = ["libnss3", "libatk1.0-0", "libatk-bridge2.0-0", "libcups2", "libgbm1", "libasound2t64", "libpangocairo-1.0-0", "libxss1", "libgtk-3-0", "libxshmfence1", "libglu1", "chromium", "curl", "wget"]

[start]
cmd = "npm run start"
